# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.define "acs" do |acs|
		acs.vm.box = "ubuntu/xenial32"
		acs.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1", auto_correct: true
		acs.vm.network "private_network", ip: "192.168.10.100"
		acs.vm.network "public_network"
		acs.vm.provider "virtualbox" do |vb|
			vb.name = "zabbix"
			#vb.group = "TEST"
			#vb.gui = true
			#vb.memory = "1024"
		end

		acs.vm.provision "shell", inline: <<-SHELL
			sudo apt-get update
			sudo apt-get -y upgrade
			echo "Getting .db from zabbix repo -----------------------------------------------------------------------------"
			sudo wget http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.2-1+xenial_all.deb
			sudo dpkg -i zabbix-release_3.2-1+xenial_all.deb
			echo "Installing Apached, MYSQL, PHP ---------------------------------------------------------------------------"
			sudo apt-get update
			sudo apt-get install -y apache2 tasksel
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
			#sudo apt-get -y install mysql-server
			sudo tasksel install lamp-server
			echo "Installing Zabbix and its dependencies -------------------------------------------------------------------"
			sudo apt-get -y install zabbix-server-mysql zabbix-frontend-php
			sudo apt-get -y install php-bcmath php-mbstring php-xmlwriter php-xmlreader

			#shell> mysql -uroot -p
			echo "Creating zabbix db"
			mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS zabbix character set utf8 collate utf8_bin;"
			echo "grant permissions to db"
			mysql -uroot -proot -e "grant all privileges on zabbix.* to zabbix@localhost identified by 'zabbix';"
			zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mysql -uzabbix -pzabbix zabbix
			#password = zabbix
			sudo cp /vagrant/files/zabbix/zabbix_server.conf /etc/zabbix/zabbix_server.conf
			sudo cp /vagrant/files/zabbix/apache.conf /etc/zabbix/apache.conf
			sudo service zabbix-server start
			sudo update-rc.d zabbix-server enable

			sudo service apache2 restart
			sudo apt-get -y install zabbix-agent
			sudo service zabbix-agent start
		SHELL
	end
	config.vm.define "Win10" do |win10|
		# to export updates to the .box run this
		win10.vm.box = "C:/Vagrant_boxes/Win10ver2.box"
		win10.vm.guest = :windows
		win10.vm.communicator = "winrm"
		win10.vm.boot_timeout = 600
		win10.vm.graceful_halt_timeout = 600
		win10.vm.network :forwarded_port, guest: 3389, host: 3389, auto_correct: true
		win10.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
		#win10.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
		win10.vm.synced_folder "./", "/vagrant" #, type: "smb"
		win10.vm.synced_folder "../", "/bin" #, type: "smb"

		win10.vm.provider "virtualbox" do |vb|
			vb.gui = true
			vb.name = "Win 10 Support VM1"
			vb.memory = "1024"
		end
		#
		# View the documentation for the provider you are using for more
		# information on available options.
		# Enable provisioning with a shell script. Additional provisioners such as
		# Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
		# documentation for more information about their specific syntax and use.
		#win10.vm.provision :shell, :path => "scripts/InstallChocolatey.ps1"
		#win10.vm.provision "shell", inline: <<-SHELL
			#choco install -Y google-chrome-x64
			#choco install -Y git putty.install
			#choco install -Y git
			#choco install -Y github winscp
			#choco install -Y windirstat
			#choco install -Y baretail
			#choco install -Y notepadplusplus -x86
			#choco install -Y rdcman
			#choco install -Y selenium-chrome-driver
			#choco install -Y selenium-ie-driver
			#choco install -Y selenium-all-drivers
			#choco install -Y seleniumhub
			#choco install -Y mremoteng
			#choco install -Y curl
			#choco install -Y wireshark
		#SHELL
	end



	config.vm.define "db" do |db|
		db.vm.box = "C:/Vagrant_boxes/Windows_Server_2012_R2.box"
		db.vm.network "private_network", ip: "192.168.10.110"
		db.vm.guest = :windows
		db.vm.communicator = "winrm"
		db.vm.boot_timeout = 600
		db.vm.graceful_halt_timeout = 600
		db.vm.network :forwarded_port, guest: 3389, host: 3390
		db.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
		db.winrm.username = "Administrator"
		db.winrm.password = "Asap1234"
		db.vm.provider "virtualbox" do |vb|
		#   # Display the VirtualBox GUI when booting the machine
			vb.name = "db"
			#vb.groups = "TEST"
			vb.gui = true
			vb.memory = "1024"
		end
		db.vm.provision "shell", inline: <<-SHELL
	#	C:/vagrant/ansible/ConfigureRemotingForAnsible.ps1
		SHELL
	end

end
